"""Markdown reporter — human-readable audit report."""

from datetime import datetime
from audit.scanner import AuditReport
from audit.reporters import BaseReporter


class MarkdownReporter(BaseReporter):
    """Generate a comprehensive markdown audit report."""

    SEVERITY_EMOJI = {
        "critical": "\U0001f534",  # red circle
        "high": "\U0001f7e0",      # orange circle
        "medium": "\U0001f7e1",    # yellow circle
        "low": "\U0001f7e2",       # green circle
        "info": "\U0001f535",      # blue circle
    }

    def generate(self, report: AuditReport) -> str:
        summary = report.summary()
        lines: list[str] = []
        lines.append("# Rogue Agent Audit Report")
        lines.append("")
        lines.append(f"**Target:** `{report.target}`")
        lines.append(f"**Date:** {report.timestamp}")
        lines.append(f"**Duration:** {report.scan_duration_ms}ms")
        lines.append(f"**Tool:** Rogue Agent Audit v0.1.0")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(f"This audit scanned **{report.target}** for ungoverned, unregistered, or potentially")
        lines.append("unauthorised AI agent activity. A total of **{0}** findings were identified.".format(summary["total_findings"]))
        lines.append("")

        if report.has_critical_findings:
            lines.append("> \u26a0\ufe0f **Critical findings detected.** Immediate investigation recommended.")
            lines.append("")

        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        for sev in ("critical", "high", "medium", "low", "info"):
            emoji = self.SEVERITY_EMOJI.get(sev, "\u26aa")
            count = summary["by_severity"].get(sev, 0)
            lines.append(f"| {emoji} {sev.capitalize()} | {count} |")
        lines.append("")
        lines.append(f"**Ungoverned agents detected:** {report.ungoverned_agent_count}")
        lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("## Detailed Findings")
        lines.append("")

        if not report.findings:
            lines.append("*No findings were detected.*")
            lines.append("")

        for i, f in enumerate(report.findings, 1):
            emoji = self.SEVERITY_EMOJI.get(f.severity, "\u26aa")
            lines.append(f"### {emoji} Finding {i}: {f.title}")
            lines.append("")
            lines.append(f"| Field | Value |")
            lines.append(f"|-------|-------|")
            lines.append(f"| Detector | `{f.detector}` |")
            lines.append(f"| Severity | **{f.severity.upper()}** |")
            lines.append(f"| Agent Type | {f.agent_type or 'Unknown'} |")
            lines.append("")
            lines.append(f"**Description:** {f.description}")
            lines.append("")
            if f.evidence:
                lines.append(f"**Evidence:**")
                lines.append("")
                lines.append("```")
                lines.append(f"{f.evidence}")
                lines.append("```")
                lines.append("")
            if f.recommendation:
                lines.append(f"**Recommendation:** {f.recommendation}")
                lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("## Remediation Guide")
        lines.append("")
        lines.append("Findings marked **critical** or **high** should be addressed immediately:")
        lines.append("")
        lines.append("1. **Register all agents** \u2014 Ensure every AI agent in your environment is catalogued")
        lines.append("2. **Apply governance** \u2014 Deploy a runtime governance layer to enforce policies")
        lines.append("3. **Monitor continuously** \u2014 Set up ongoing monitoring for new agent deployments")
        lines.append("4. **Revoke unauthorised access** \u2014 Remove API keys and credentials for unregistered agents")
        lines.append("")
        lines.append("---")
        lines.append("")
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
        lines.append(f"*Report generated by Rogue Agent Audit v0.1.0 on {now}*")
        lines.append("*Companion project: [Agent Asset Registry](https://github.com/narko4u/witnessos-agent-asset-registry)*")
        lines.append("*Interested in governance? [WitnessOS](https://github.com/narko4u/witnessos)*")

        return "\n".join(lines)
